name: GitTime
options:
  bundleIdPrefix: io.github.87kangsw
  deploymentTarget:
    iOS: '14.0'
  usesTabs: true
  indentWidth: 4
  tabWidth: 4
  generateEmptyDirectories: true
  useCocoaPods: false
packages:
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    from: 3.2.0
  RxSwift: 
    url: https://github.com/ReactiveX/RxSwift
    from: 6.2.0
  RxDataSources:
    url: https://github.com/RxSwiftCommunity/RxDataSources
    from: 5.0.0
  RxOptional:
    url: https://github.com/RxSwiftCommunity/RxOptional
    from: 5.0.2
  Moya:
    url: https://github.com/Moya/Moya
    from: 15.0.0 
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.1
  PanModal:
    url: https://github.com/slackhq/PanModal
    from: 1.2.7         
  KeychainAccess:  
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.2
  RealmSwift:
    url: https://github.com/realm/realm-swift
    from: 10.49.2
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 7.10.2
  SwiftyBeaver:
    url: https://github.com/SwiftyBeaver/SwiftyBeaver
    from: 2.0.2
  Kanna:
    url: https://github.com/tid-kijyun/Kanna.git  
    from: 5.3.0
  Then:
    url: https://github.com/devxoul/Then
    from: 2.7.0
  AcknowList:  
    url: https://github.com/vtourraine/AcknowList    
    from: 3.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.24.0
  Toaster:
    url: https://github.com/devxoul/Toaster.git
    branch: master
  GitHubKit:
    url: https://github.com/87kangsw/GitHubKit
    from: 1.0.1  
fileGroups:
  - GitTime/Supporting Files
targets:
  GitTime:
    platform: iOS
    type: application
    deploymentTarget: '14.0'
    entitilements:
      path: GitTime/Supporting Files/GitTime.entitlements
    scheme:
      testTargets:
        - GitTimeTests
    sources:
      - path: 'GitTime/Sources'
        type: group
      - path: 'GitTime/Supporting Files'
        type: group
      - path: 'GitTime/Resources'
        type: group
    # postCompileScripts:
    #   - path: BuildScripts/SwiftLint.sh
    #     name: Swiftlint
    postBuildScripts:
      - path: BuildScripts/FirebaseCrashlytics.sh
        name: Firebase Crashlytics
    settings:
      INFOPLIST_FILE: GitTime/Supporting Files/Info.plist
      DEVELOPMENT_TEAM: R46Q3HW9V3
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      OTHER_LDFLAGS: -ObjC $(inherited)
    dependencies:
      - package: ReactorKit
      - package: RxSwift
        product: RxCocoa
      - package: RxDataSources
      - package: RxOptional  
      - package: Moya
        product: Moya
      - package: Moya        
        product: RxMoya
      - package: SnapKit
      - package: PanModal
      - package: KeychainAccess  
      - package: RealmSwift
        product: Realm
      - package: RealmSwift        
        product: RealmSwift
      - package: Kingfisher
      - package: SwiftyBeaver
      - package: Kanna
      - package: Then
      - package: AcknowList
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase        
        product: FirebaseCrashlytics
      - package: Firebase        
        product: FirebaseAuth
      - package: Firebase    
        product: FirebasePerformance
      - package: Toaster
      - package: GitHubKit
  GitTimeTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - GitTimeTests
    dependencies:
      - target: GitTime
