name: GitTime
options:
  bundleIdPrefix: io.github.87kangsw
  deploymentTarget:
    iOS: '13.0'
  usesTabs: true
  indentWidth: 4
  tabWidth: 4
  generateEmptyDirectories: true
packages:
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    from: 3.0.0
fileGroups:
  - GitTime/Supporting Files
targets:
  GitTime:
    platform: iOS
    type: application
    deploymentTarget: '13.0'
    entitilements:
      path: GitTime/Supporting Files/GitTime.entitlements
    scheme:
      testTargets:
        - GitTimeTests
    sources:
      - path: 'GitTime/Sources'
        type: group
      - path: 'GitTime/Supporting Files'
        type: group
      - path: 'GitTime/Resources'
        type: group
    postCompileScripts:
      - path: BuildScripts/SwiftLint.sh
        name: Swiftlint
    postBuildScripts:
      - path: BuildScripts/FirebaseCrashlytics.sh
        name: Firebase Crashlytics
    settings:
      INFOPLIST_FILE: GitTime/Supporting Files/Info.plist
      DEVELOPMENT_TEAM: R46Q3HW9V3
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
      - package: ReactorKit  
  GitTimeTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - GitTimeTests
    dependencies:
      - target: GitTime
