default_platform :ios

platform :ios do

  before_all do
    ensure_git_status_clean(show_uncommitted_changes: true)
  end

  desc "Beta Deployment to TestFlight"
  lane :develop do | options |

    changelog = read_changelog(
      changelog_path: './CHANGELOG.md',
      section_identifier: '[Unreleased]',
      excluded_markdown_elements: ['-', '###']
    )

    version_number = get_version_number(xcodeproj: ENV['XCODEPROJ_NAME'])
    build_number = get_build_number(xcodeproj: ENV['XCODEPROJ_NAME'])

    output_name = “#{ENV[‘IPA_NAME’]}_#{version_number}(#{build_number}).ipa”
    full_output = “#{ENV[‘FASTLANE_PATH’]}#{version_number}/#{time.strftime(“%Y-%m-%d”)}/Build(#{build_number})#{ENV[‘DEVELOP_IPA_PATH’]}”

    add_badge(shield: "#{version_number}-#{build_number}-dark", no_badge: true)

    match(
      type: "development",
      app_identifier: ENV['APPLE_APP_IDENTIFIER'],
      readonly: true
    )

    gym(
      workspace: ENV['XCWORKSPACE_NAME'],
      include_bitcode: true,
      clean: true,
      include_symbols: true,
      output_directory: full_output,
      output_name: output_name,
      export_method: "development"
    )

    upload_to_testflight

  end

  after_all do |lane|
    clean_build_artifacts # Deletes files created as result of running gym, cert, sigh or download_dsyms
    reset_git_repo(skip_clean: true) # Resets git repo to a clean state by discarding uncommitted changes
    version_number = get_version_number(xcodeproj: ENV['XCODEPROJ_NAME'])
    build_number = get_build_number(xcodeproj: ENV['XCODEPROJ_NAME'])
    message_to_slack(
      version: version_number,
      build: build_number,
      changelog: changelog,
      beta: true
    )
  end

  error do |lane, exception|
    clean_build_artifacts # Deletes files created as result of running gym, cert, sigh or download_dsyms
    reset_git_repo(skip_clean: true) # Resets git repo to a clean state by discarding uncommitted changes
    version_number = get_version_number(xcodeproj: ENV['XCODEPROJ_NAME'])
    build_number = get_build_number(xcodeproj: ENV['XCODEPROJ_NAME'])
    slack(
      slack_url: ENV['SLACK_URL'],
      success: false,
      message: "TestFlight upload failed #{exception.message}."
    )
  end

end

